### PR TITLE
Patches from FreeBSD ports tree

### PR DESCRIPTION
**Pull request by rozhuk-im**

### CODE REVIEW

**Comment by rayddteam** [comment]
Thanks, Ivan!

**Comment by rozhuk-im** [comment]
You are welcome!

Will you bump version?
I can make PR to switch from autotools to cmake, if you wish.

**Comment by rayddteam** [comment]
> You are welcome!
> 
> Will you bump version?
> I can make PR to switch from autotools to cmake, if you wish.

done, 0.0.5

**Comment by rozhuk-im** [comment]
You only set tag, but inside still 0.0.4
https://github.com/rayddteam/xf86-video-scfb/commit/bdeb3bf153d6f841f15990119c07ee349c29866a - prev version bump commit.

**Comment by rayddteam** [comment]
Ohh, sorry. Much time left :)
Is it looks fine now?

**Comment by rozhuk-im** [comment]
https://github.com/rayddteam/xf86-video-scfb/releases
0.0.0? :)

**Comment by rayddteam** [comment]
heh, fixed :)

**Comment by rozhuk-im** [comment]
Thanks!

**Pull request merged**
